name: Spam Classifier CI/CD

on:
  push:
    branches: [ mlop-pipeline ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/upload-artifact@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: 3.10

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Download dataset
      run: |
        curl -L -o spam.csv https://raw.githubusercontent.com/justmarkham/pycon-2016-tutorial/master/data/spam.csv

    - name: Train Spam Classifier
      run: python train_spam_classifier.py

    - name: Evaluate Spam Classifier
      run: python evaluate_spam_classifier.py

    - name: Upload model artifact
      uses: actions/upload-artifact@v3
      with:
        name: spam-model
        path: |
          spam_model.joblib
          vectorizer.joblib
